language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- sls deploy
env:
  global:
    secure: ZdIaMOShikYal36qzI2eig2AHZRzU8iofL9hIr6Ea7qna9WbvTzNnPCHuW3S20pfbLbPpHz8dCQX+bicUU3f//smu03NHGVHqLoJqBgQW3p1dPmrjNL1Vy8M/ob1BmzDK+JEGoMD/4V0nDfGy59qXXZHmoFuifo97nPSJCYEVK8ZKr5fudpANjc0ox0gP7Wjih0lJONllFbDDi+rWysZ4sO+mo+m7zRJyDeWYmDQK/U+t64B7lIVx2tfGgcuHruXTmJ4aEc+zueH6iUZyZFOik1DImuvVNNnCT8PLeCve4bT+aOd9gPZbUz8udNDZM61EyZSCR1aqCisUL8blWBQEWC0Z0BHDCsYXvfss7vgQ8mf1lTzpSDI6wmp3bVaGA39sv5H/6Ca+v0c5+lkcXxKGX90pxnRzpKX29rhcKiNd8airUYtuFNxWlBsf7e1+7EP3OTUGhtvJAJZJP8Wqtu/nEa3iPDz2HvxfjBsP741/AaYDgXlLy9aaWqoPyhOcNevkCgclwmTIyHOe9oOS/tleSo+OwihjeBggqH2ZOH2Ik6a9dtXgKPkL2PD2DKU3uxjgNq8Kpd4/ZNSzbHvgSzK0iQtn9uxNoGVIB55V7D8RvPXuT+p+/7mvUN6bR+UUEDZP/L7cIt5NFWApfPkifv5gI3/QKTE+xA0T1FLktyti8w=
