service: naming-service

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 128
  timeout: 30
  environmet:
    RDS_HOST: ''
    RDS_PORT: ''
    RDS_DB: ''
    RDS_LOGIN: ''
    RDS_PASSWORD: ''

functions:
  generateName:
    handler: restHandler.generateAllianceName
    events:
      - http:
          path: name/alliance/generate
          method: get
          cors:
            origins:
              - '*'
