service: naming-service

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 128
  timeout: 30

functions:
  generateName:
    handler: restHandler.generateAllianceName
    events:
      - http:
          path: name/alliance/generate
          method: get
          cors:
            origins:
              - '*'
